/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master handler for getting a variables name, short name, etc.
*/
private["_var","_mode"];
_var = param [0,"",[""]];
_mode = param [1,-1,[0]];
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "trackDart": {"life_inv_trackDart"};
			case "tacTrig": {"life_inv_tacTrig"};
			case "alarmV": {"life_inv_alarmV"};
			case "hightoolkit": {"life_inv_toolkit"};
			case "medkit": {"life_inv_medkit"};
			case "detector": {"life_inv_detector"};
			case "bhTool": {"life_inv_bhTool"};
			case "ammoBox": {"life_inv_ammoBox"};
			case "nitro": {"life_inv_nitro"};
			case "tentciv": {"life_inv_tentciv"};
			case "ammoBoxS": {"life_inv_ammoBoxS"};
			case "diamondf": {"life_inv_diamondf"};
			case "plate": {"life_inv_plate"};
			case "plateMetal": {"life_inv_plateMetal"};
			case "roadCone": {"life_inv_roadCone"};
			case "roadBarrier": {"life_inv_roadBarrier"};
			case "cncBarrier": {"life_inv_cncBarrier"};
			case "cncBarrierL": {"life_inv_cncBarrierL"};
			case "barGate": {"life_inv_barGate"};
			case "shank": {"life_inv_shank"};
			case "excavator": {"life_inv_excavator"};
			case "pearl": {"life_inv_pearl"};
			case "doubl": {"life_inv_doubl"};
			case "ruby": {"life_inv_ruby"};
			case "silver": {"life_inv_silver"};
			case "gpstracker": {"life_inv_gpstracker"};
			case "ied": {"life_inv_ied"};
			case "eph": {"life_inv_eph"};
			case "hydro": {"life_inv_hydro"};
			case "phos": {"life_inv_phos"};
			case "meth": {"life_inv_meth"};
			case "vammo": {"life_inv_vammo"};
			case "blindfold": {"life_inv_blindfold"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "coffee": {"life_inv_coffee"};
			case "donuts": {"life_inv_donuts"};
			case "fuelE": {"life_inv_fuelE"};
			case "fuelF": {"life_inv_fuelF"};
			case "money": {"life_handpaper"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "ironr": {"life_inv_ironr"};
			case "copperr": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "saltr": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondc"};
			case "cocaine": {"life_inv_cocaine"};
			case "cocainep": {"life_inv_cocainep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "zip": {"life_inv_zip"};
			case "goldbar": {"life_inv_goldbar"};
			case "goldore": {"life_inv_goldore"};
			case "goldr": {"life_inv_goldr"};
			case "blastingcharge": {"life_inv_blastingcharge"};
			case "boltcutter": {"life_inv_boltcutter"};
			case "defusekit": {"life_inv_defusekit"};
			case "storagesmall": {"life_inv_storagesmall"};
			case "storagebig": {"life_inv_storagebig"};
			case "alarm": {"life_inv_alarm"};
			case "reinforceddoor": {"life_inv_reinforceddoor"};
			case "steeldoor": {"life_inv_steeldoor"};
			case "corn": {"life_inv_corn"};
			case "moonshine": {"life_inv_moonshine"};
			case "fcrab": {"life_inv_fcrab"};
			case "fcrabp": {"life_inv_fcrabp"};
			case "mcrabs": {"life_inv_mcrabs"};
			case "mcrab": {"life_inv_mcrab"};
			case "crabpot" : {"life_inv_crabpot"};
			case "coalore" : {"life_inv_coalore"};
			case "steel" : {"life_inv_steel"};
			case "defib" : {"life_inv_defib"};
			case "log" : {"life_inv_log"};
			case "lumber" : {"life_inv_lumber"};
			case "chainsaw" : {"life_inv_chainsaw"};
			case "cellphone" : {"life_inv_cellphone"};
			case "RoadConeStrip": {"life_inv_RoadConeStrip"};
			case "RoadBlockWood": {"life_inv_RoadBlockWood"};
       		case "lethal": {"life_inv_lethal"};
			case "lethali": {"life_inv_lethali"};
		};
	};
	
	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_trackDart": {"trackDart"};
			case "life_inv_tacTrig": {"tacTrig"};
			case "life_inv_toolkit": {"hightoolkit"};
			case "life_inv_alarmV": {"alarmV"};
			case "life_inv_detector": {"detector"};
			case "life_inv_ammoBoxS": {"ammoBoxS"};
			case "life_inv_ammoBox": {"ammoBox"};
			case "life_inv_medkit": {"medkit"};
			case "life_inv_diamondf": {"diamondf"};
			case "life_inv_plateMetal": {"plateMetal"};
			case "life_inv_nitro": {"nitro"};
			case "life_inv_plate": {"plate"};
			case "life_inv_excavator": {"excavator"};
			case "life_inv_silver": {"silver"};
			case "life_inv_roadCone": {"roadCone"};
			case "life_inv_bhTool": {"bhTool"};
			case "life_inv_tentciv": {"tentciv"};
			case "life_inv_roadBarrier": {"roadBarrier"};
			case "life_inv_cncBarrier": {"cncBarrier"};
			case "life_inv_cncBarrierL": {"cncBarrierL"};
			case "life_inv_barGate": {"barGate"};
			case "life_inv_shank": {"shank"};
			case "life_inv_ruby": {"ruby"};
			case "life_inv_doubl": {"doubl"};
			case "life_inv_pearl": {"pearl"};
			case "life_inv_gpstracker": {"gpstracker"};
			case "life_inv_ied": {"ied"};
			case "life_inv_eph": {"eph"};
			case "life_inv_phos": {"phos"};
			case "life_inv_meth": {"meth"};
			case "life_inv_hydro": {"hydro"};
			case "life_inv_vammo": {"vammo"};
			case "life_inv_blindfold": {"blindfold"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelE": {"fuelE"};
			case "life_inv_fuelF": {"fuelF"};
			case "life_handpaper": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"ironr"};
			case "life_inv_copperr": {"copperr"};
			case "life_inv_goldore": {"goldore"};
			case "life_inv_goldr": {"goldr"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondc": {"diamondc"};
			case "life_inv_saltr": {"saltr"};
			case "life_inv_cocaine": {"cocaine"};
			case "life_inv_cocainep": {"cocainep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_blastingcharge": {"blastingcharge"};
			case "life_inv_boltcutter": {"boltcutter"};
			case "life_inv_defusekit": {"defusekit"};
			case "life_inv_alarm": {"alarm"};
			case "life_inv_reinforceddoor": {"reinforceddoor"};
			case "life_inv_steeldoor": {"steeldoor"};		
            case "life_inv_crowbar": {"crowbar"};
			case "life_inv_lethal": {"lethal"};
			case "life_inv_lethali": {"lethali"};
			case "life_inv_lumber" : {"lumber"};
			case "life_inv_chainsaw" : {"chainsaw"};
			case "life_inv_cellphone" : {"cellphone"};
			case "life_inv_RoadConeStrip": {"RoadConeStrip"};
			case "life_inv_RoadBlockWood": {"RoadBlockWood"};
			case "life_inv_corn": {"corn"};
			case "life_inv_moonshine": {"moonshine"};
			case "life_inv_fcrab": {"fcrab"};
			case "life_inv_fcrabp": {"fcrabp"};
			case "life_inv_mcrabs": {"mcrabs"};
			case "life_inv_mcrab": {"mcrab"};
			case "life_inv_crabpot": {"crabpot"};
			case "life_inv_coalore": {"coalore"};
			case "life_inv_steel": {"steel"};
			case "life_inv_defib" : {"defib"};
			case "life_inv_log" : {"log"};
			case "life_inv_rock": {"rock"};
			case "life_inv_zip": {"zip"};
		};
	};
};
